name: Project Provisioning

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

env:
  PATH_TO_TFSCRIPT_BTP: 'infra/BTP'
  PATH_TO_TFSCRIPT_CF: 'infra/CloudFoundry'

jobs:

###
# DEVELOPMENT
###
  create_subaccount_dev:
    concurrency:
     group: dev
     cancel-in-progress: true

    name: Create DEV Subaccount for Project
    if: ${{ !github.event.issue.pull_request }} && contains(github.event.issue.body, 'Project Name')
    runs-on: ubuntu-latest
    environment: dev
    env:
      STAGE: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Issue Data
        id: extract_data
        uses: issue-ops/parser@v4
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: account_request.yml

      - name: Output Issue JSON
        id: output_issue_data
        run: |
          echo '${{ steps.extract_data.outputs.json }}' | jq '.' > local.json
          echo "project-name=$(jq -r '."project-name"' local.json)" >> $GITHUB_OUTPUT
          echo "cost-center=$(jq -r '."cost-center"' local.json)" >> $GITHUB_OUTPUT
          echo "space-responsible=$(jq -r '."space-responsible"' local.json)" >> $GITHUB_OUTPUT
          echo "subaccount-region=$(jq -r '."subaccount-region"[0]' local.json)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: Init Terraform for BTP
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} init \
             -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
             -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
             -no-color

      - name: Terraform Apply for BTP
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
            export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
            export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
            export TF_VAR_project_name='${{ steps.output_issue_data.outputs.project-name }}'
            export TF_VAR_subaccount_region=${{ steps.output_issue_data.outputs.subaccount-region }}
            export TF_VAR_subaccount_stage=DEV
            export TF_VAR_project_costcenter=${{ steps.output_issue_data.outputs.cost-center }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} workspace select -or-create=true ${{ env.STAGE }}  && terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} apply -auto-approve -no-color

      - name: Transfer BTP output values
        id: terraform_output_btp
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} workspace select ${{ env.STAGE }} && terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} output -json > output_btp.json
          echo "cf_api_url=$(jq -r '.cf_api_url.value' output_btp.json)" >> $GITHUB_OUTPUT
          echo "cf_org_id=$(jq -r '.cf_org_id.value' output_btp.json)" >> $GITHUB_OUTPUT
          echo "subaccount_url=$(jq -r '.subaccount_url.value' output_btp.json)" >> $GITHUB_OUTPUT

      - name: Init Terraform for CF
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} init  \
             -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
             -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
             -no-color

      - name: Terraform Apply for CF
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            export CF_USER=${{ secrets.BTP_USERNAME }}
            export CF_PASSWORD=${{ secrets.BTP_PASSWORD }}
            export TF_VAR_project_name='${{ steps.output_issue_data.outputs.project-name }}'
            export TF_VAR_subaccount_stage=DEV
            export TF_VAR_cf_org_id=${{ steps.terraform_output_btp.outputs.cf_org_id }}
            export TF_VAR_cf_api_url=${{ steps.terraform_output_btp.outputs.cf_api_url }}
            export TF_VAR_subaccount_url=${{ steps.terraform_output_btp.outputs.subaccount_url }}
            export TF_VAR_cf_space_manager=${{ steps.output_issue_data.outputs.space-responsible }}
            export TF_VAR_cf_space_developer=${{ steps.output_issue_data.outputs.space-responsible }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} workspace select -or-create=true ${{ env.STAGE }} && terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} apply -auto-approve -no-color

      - name: Transfer Cloud Foundry output values
        id: terraform_output_cf
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} workspace select ${{ env.STAGE }} &&  terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} output -json > output_cf.json
            echo "cf_space_url=$(jq -r '.cf_space_url.value' output_cf.json)" >> $GITHUB_OUTPUT

      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The DEV subaccount for the project has been created successfully 🎉

            Here is the relevant information for the project team:

              Subaccount URL - Stage DEV: ${{ steps.terraform_output_btp.outputs.subaccount_url }}
              CF API URL - Stage DEV: ${{ steps.terraform_output_btp.outputs.cf_api_url }}
              CF Space URL - Stage DEV: ${{ steps.terraform_output_cf.outputs.cf_space_url }}

            🚀 Build some awesome apps with it!

###
# TESTING
###
  create_subaccount_test:
    # Create Test subacount only if DEV was provisioned successfully
    needs: create_subaccount_dev
    concurrency:
     group: test
     cancel-in-progress: true
    name: Create TEST Subaccount for Project
    if: ${{ !github.event.issue.pull_request }} && contains(github.event.issue.body, 'Project Name')
    runs-on: ubuntu-latest
    environment: test
    env:
      STAGE: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Issue Data
        id: extract_data
        uses: issue-ops/parser@v4
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: account_request.yml

      - name: Output Issue JSON
        id: output_issue_data
        run: |
          echo '${{ steps.extract_data.outputs.json }}' | jq '.' > local.json
          echo "project-name=$(jq -r '."project-name"' local.json)" >> $GITHUB_OUTPUT
          echo "cost-center=$(jq -r '."cost-center"' local.json)" >> $GITHUB_OUTPUT
          echo "space-responsible=$(jq -r '."space-responsible"' local.json)" >> $GITHUB_OUTPUT
          echo "subaccount-region=$(jq -r '."subaccount-region"[0]' local.json)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: Init Terraform for BTP
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} init  \
             -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
             -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
             -no-color

      - name: Terraform Apply for BTP
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
            export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
            export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
            export TF_VAR_project_name='${{ steps.output_issue_data.outputs.project-name }}'
            export TF_VAR_subaccount_region=${{ steps.output_issue_data.outputs.subaccount-region }}
            export TF_VAR_subaccount_stage=TEST
            export TF_VAR_project_costcenter=${{ steps.output_issue_data.outputs.cost-center }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} workspace select -or-create=true ${{ env.STAGE }} && terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} apply -auto-approve -no-color

      - name: Transfer BTP output values
        id: terraform_output_btp
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} workspace select ${{ env.STAGE }} && terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} output -json > output_btp.json
          echo "cf_api_url=$(jq -r '.cf_api_url.value' output_btp.json)" >> $GITHUB_OUTPUT
          echo "cf_org_id=$(jq -r '.cf_org_id.value' output_btp.json)" >> $GITHUB_OUTPUT
          echo "subaccount_url=$(jq -r '.subaccount_url.value' output_btp.json)" >> $GITHUB_OUTPUT

      - name: Init Terraform for CF
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} init  \
             -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
             -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
             -no-color

      - name: Terraform Apply for CF
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            export CF_USER=${{ secrets.BTP_USERNAME }}
            export CF_PASSWORD=${{ secrets.BTP_PASSWORD }}
            export TF_VAR_project_name='${{ steps.output_issue_data.outputs.project-name }}'
            export TF_VAR_subaccount_stage=TEST
            export TF_VAR_cf_org_id=${{ steps.terraform_output_btp.outputs.cf_org_id }}
            export TF_VAR_cf_api_url=${{ steps.terraform_output_btp.outputs.cf_api_url }}
            export TF_VAR_subaccount_url=${{ steps.terraform_output_btp.outputs.subaccount_url }}
            export TF_VAR_cf_space_manager=${{ steps.output_issue_data.outputs.space-responsible }}
            export TF_VAR_cf_space_developer=${{ steps.output_issue_data.outputs.space-responsible }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} workspace select -or-create=true ${{ env.STAGE }} && terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} apply -auto-approve -no-color

      - name: Transfer Cloud Foundry output values
        id: terraform_output_cf
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} workspace select ${{ env.STAGE }} &&  terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} output -json > output_cf.json
            echo "cf_space_url=$(jq -r '.cf_space_url.value' output_cf.json)" >> $GITHUB_OUTPUT

      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The TEST subaccount for the project has been created successfully 🎉

            Here is the relevant information for the project team:

              Subaccount URL - Stage TEST: ${{ steps.terraform_output_btp.outputs.subaccount_url }}
              CF API URL - Stage TEST: ${{ steps.terraform_output_btp.outputs.cf_api_url }}
              CF Space URL - Stage TEST: ${{ steps.terraform_output_cf.outputs.cf_space_url }}

            🚀 Test your awesome apps with it!

####
## PRODUCTION
####
  create_subaccount_prod:
    # Create Test subacount only if DEV and TEST was provisioned successfully
    needs: [create_subaccount_dev,create_subaccount_test]
    concurrency:
     group: prod
     cancel-in-progress: true

    name: Create PROD Subaccount for Project
    if: ${{ !github.event.issue.pull_request }} && contains(github.event.issue.body, 'Project Name')
    runs-on: ubuntu-latest
    environment: prod
    env:
      STAGE: prod
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Issue Data
        id: extract_data
        uses: issue-ops/parser@v4
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: account_request.yml

      - name: Output Issue JSON
        id: output_issue_data
        run: |
          echo '${{ steps.extract_data.outputs.json }}' | jq '.' > local.json
          echo "project-name=$(jq -r '."project-name"' local.json)" >> $GITHUB_OUTPUT
          echo "cost-center=$(jq -r '."cost-center"' local.json)" >> $GITHUB_OUTPUT
          echo "space-responsible=$(jq -r '."space-responsible"' local.json)" >> $GITHUB_OUTPUT
          echo "subaccount-region=$(jq -r '."subaccount-region"[0]' local.json)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: Init Terraform for BTP
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} init  \
             -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
             -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
             -no-color

      - name: Terraform Apply for BTP
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
            export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
            export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
            export TF_VAR_project_name='${{ steps.output_issue_data.outputs.project-name }}'
            export TF_VAR_subaccount_region=${{ steps.output_issue_data.outputs.subaccount-region }}
            export TF_VAR_subaccount_stage=PROD
            export TF_VAR_project_costcenter=${{ steps.output_issue_data.outputs.cost-center }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} workspace select -or-create=true ${{ env.STAGE }} && terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} apply -auto-approve -no-color

      - name: Transfer BTP output values
        id: terraform_output_btp
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} workspace select ${{ env.STAGE }} &&  terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} output -json > output_btp.json
          echo "cf_api_url=$(jq -r '.cf_api_url.value' output_btp.json)" >> $GITHUB_OUTPUT
          echo "cf_org_id=$(jq -r '.cf_org_id.value' output_btp.json)" >> $GITHUB_OUTPUT
          echo "subaccount_url=$(jq -r '.subaccount_url.value' output_btp.json)" >> $GITHUB_OUTPUT

      - name: Init Terraform for CF
        shell: bash
        run: |
          export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} init  \
             -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
             -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
             -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
             -no-color

      - name: Terraform Apply for CF
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            export CF_USER=${{ secrets.BTP_USERNAME }}
            export CF_PASSWORD=${{ secrets.BTP_PASSWORD }}
            export TF_VAR_project_name='${{ steps.output_issue_data.outputs.project-name }}'
            export TF_VAR_subaccount_stage=PROD
            export TF_VAR_cf_org_id=${{ steps.terraform_output_btp.outputs.cf_org_id }}
            export TF_VAR_cf_api_url=${{ steps.terraform_output_btp.outputs.cf_api_url }}
            export TF_VAR_subaccount_url=${{ steps.terraform_output_btp.outputs.subaccount_url }}
            export TF_VAR_cf_space_supporter=${{ steps.output_issue_data.outputs.space-responsible }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} workspace select -or-create=true ${{ env.STAGE }} && terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} apply -auto-approve -no-color

      - name: Transfer Cloud Foundry output values
        id: terraform_output_cf
        shell: bash
        run: |
            export ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} workspace select ${{ env.STAGE }} &&  terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} output -json > output_cf.json
            echo "cf_space_url=$(jq -r '.cf_space_url.value' output_cf.json)" >> $GITHUB_OUTPUT

      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The PROD subaccount for the project has been created successfully 🎉

            Here is the relevant information for the project team:

              Subaccount URL - Stage PROD: ${{ steps.terraform_output_btp.outputs.subaccount_url }}
              CF API URL - Stage PROD: ${{ steps.terraform_output_btp.outputs.cf_api_url }}
              CF Space URL - Stage PROD: ${{ steps.terraform_output_cf.outputs.cf_space_url }}

            🚀 Run your awesome apps with it!
